#str1=raw_input("Enter first string: ")
#str2=input("Enter second string: ")
#print("First string: ", str1)
#print("Second string: ", str2)
def file_io(filename,mode):
    file1=  open(filename,mode)
    print(f"file1.mode: {file1.mode}")
    print(f"file1.name: {file1.name}")
    print(f"file1.closed: {file1.closed}")
    file1.write("Hello World again \n")
    file1.write("Again This is the first file created using Python\n")
    file1.close()
    print(f"file1.closed after close(): {file1.closed}")
    #file1.seek(0)

file_io("first_file3.txt","r+")
#file_io("first_file3.txt","a+")

def read_file(filename,mode ,numberoflines=2):
    files2=open(filename,mode)
    print(" number of bytes read:")
    content=files2.read(numberoflines)
    print(content)
    #files2.close()
    print(f"current pointer after number of bytes read :{files2.tell()}")
    files2.seek(0,0)
    print(f"current pointer befire reading full content  :{files2.tell()}")
    #files3=open(filename,mode)
    content=files2.read()
    print("Read full content:")
    print(content)
   # files3.close()
    print(f"current pointer after  full read :{files2.tell()}")
    files2.seek(0,0)
    print("Reading line by line:")
    print(f"current pointer befire reading line by line  content  :{files2.tell()}")
    #file4=open(filename,mode)
    file_lines=files2.readlines()
    print(f"total lines in file:{len(file_lines)} and content is:{file_lines}")
    for i in file_lines:
        print(i)
    files2.close()

#read_file("first_file3.txt","r+",3)

def os_methods():
    import os
    #print (f"List of files and directories in current working directory:{os.listdir()}")
    print (f"current working directories:{os.getcwd()}")
    file1=open("os_test_file.txt","w+")
    file1.write("this is test file for os modile\n")
    file1.write("This file is created using os module\n")
    file1.seek(0,0)
    file1.close()
    os.rename("os_test_file.txt","renamed_os_test_file.txt")
    #print (f"List of files and directories after renaming file:{os.listdir()}")
    os.remove("renamed_os_test_file.txt")
    #os.mkdir("test_dir")
    #os.rmdir("test_dir")

#os_methods()
    #os.mkdir("new_dir")
    #os.chdir("new_dir")
    #print (f"current wokring direcotry after chnage:{os.getcwd()

